### ISSUE TITLE
implement frontend-ssr-template

### ISSUE THREAD

**Issue by Kravalg** [VilnaCRM-Org/frontend-ssr-template#2]
As a developer, I want to be able to create repositories from the frontend-ssr-template.

### Technical requirements

- [ ] [MSW](https://mswjs.io/)

### Tasks

- [x] use [website repository](https://github.com/VilnaCRM-Org/website) as an example
- [x] init template repository regarding [best practices](https://github.com/alan2207/bulletproof-react)
- [x] write website design in the [document](https://miro.com/app/board/uXjVPRE64mI=/?share_link_id=214380289179) following the [C4 model](https://c4model.com/)
- [x] Image optimization CI check (https://github.com/marketplace/actions/image-actions)
- [x] add [DI container library](https://github.com/microsoft/tsyringe)
- [x] cache pnpm work for all existing GitHub CI actions

### Subtasks

- [x] look for IAST tool and see if it can be used it our project
- [x] add artillery for load testing
- [x] add [i18n](https://www.npmjs.com/package/react-i18next) (internationalization)
- [ ] add GUI or files for i18n
- [x] add memlab to CI check (https://github.com/facebook/memlab)
- [x] add [web-vitals](https://www.npmjs.com/package/web-vitals) 
- [x] add yaml files linter
- [ ] add auto-updates for repositories that were created from the repository template (@kravalg)

### Acceptance criteria

- [ ] CI works when developer create a PR
- [ ] all tests passed
