### ISSUE TITLE
Add auto releases, template sync

### ISSUE THREAD

**Issue by TuranC** [VilnaCRM-Org/frontend-ssr-template#32]
### Description

need to update auto releases and add template sync

### Tasks

- [ ] update auto releases
- [ ] add template sync

### Acceptance Criteria

- [ ] auto releases must be working as expected
- [ ] template sync must be working as expected
