### ISSUE TITLE
Add auto releases to the project

### ISSUE THREAD

**Issue by Kravalg** [VilnaCRM-Org/frontend-ssr-template#6]
As a developer, I want to be able to don't release the project manually

### Tasks

- [x] add autorelease CI action
- [x] add autoprerelease CI action

### Acceptance criteria

- [x] CI works when the developer creates a PR
- [x] all tests passed
- [x] all CI actions works
